### ISSUE TITLE
Automatic Tests of Container Builds

### ISSUE THREAD

**Issue by rndmh3ro** [T-Systems-MMS/docker-management-container#4]
There needs to be a automatic test pipeline that tests the container builds.
A good starting place is the examples folder: https://github.com/T-Systems-MMS/docker-management-container/tree/master/examples

One probably needs to test:
* ansible requirements with:
  * "latest" versions
  * pinned versions
* pip requirements with:
  * "latest" versions
  * pinned versions
* Packages with:
  * "latest" versions
  * pinned versions
* `*_VERSION` packages with:
  * "latest" versions
  * pinned versions
* AZ_CLI_EXTENSIONS with:
  * "latest" versions
  * pinned versions

This could probably be done with a Github Action with a matrix build.

**Comment by michaelamattes** [comment]
solved with #50
