### ISSUE TITLE
feature request: add option to configure own bash customizations

### ISSUE THREAD

**Issue by kaso-mms** [T-Systems-MMS/docker-management-container#43]
It would be nice if there would be an option to configure bash customizations (stuff you would place in .bashrc or .profile e.g. like aliases), so that they can be baked directly into the image and don't need to be configured afterwards.

**Comment by rndmh3ro** [comment]
Sounds reasonable! Do you have a specific implementation in mind?

**Comment by kaso-mms** [comment]
Not really as long as it does what it's supposed to be :)

Maybe it could be handled like ansible_requirements / pip_requirements, roughly like this:
* place a reference to the custom configs into .docker_build file
* the referenced file contains the custom aliases, bash stuff e.g. (standard bash syntax)
* contents of that file will be sourced automatically when the container starts

It might be useful for somebody to reference to an directory from .docker_build file that contains multiple files with customizations (but not needed in our case).

**Comment by michaelamattes** [comment]
We will setup this as new feature with version 2.x

**Comment by michaelamattes** [comment]
solved with #50
