### ISSUE TITLE
[Enhancement] Support for versioned repositories

### ISSUE THREAD

**Issue by danellidesign** [T-Systems-MMS/docker-management-container#55]
### Description

Hey,

I'd like to request the support of versioned repositories:

While trying to add the MongoDB repository via the build.yaml, it occured, that the repository was not added correctly. Comparing them to other working repositories the main distinction was, that the MongoDB repository is further divided into versions after the distro level and before the branch level (see [MongoDB Jammy Repo](https://repo.mongodb.org/apt/ubuntu/dists/jammy/)). Therefore the release file is not found, because it is located several levels deeper, depending on the repo version. Looking into the created Dockerfile.template one can see that the distro part is solved by lsb_release. I'd like to request an extension of this part to allow the addition of versioned paths after the lsb_release var. 

### Additional information

MongoDB Repository: https://repo.mongodb.org/apt/ubuntu

**Comment by michaelamattes** [comment]
@danellidesign Thanks for the feature suggestion. We've done this by https://github.com/T-Systems-MMS/docker-management-container/pull/57
