### ISSUE TITLE
Variable or file with release tag

### ISSUE THREAD

**Issue by avalor1** [T-Systems-MMS/docker-management-container#84]
### Description

It would be nice if one could see the used version of the DMC.

Maybe as environment variable or a file named like the version or with the version in it.

**Comment by rndmh3ro** [comment]
@avalor1 does this work for you?

**Comment by avalor1** [comment]
Nope, this does not work. When using the latest Tag i cannot see this label. Neither while running the container or when inspecting the downloaded image

**Comment by michaelamattes** [comment]
Add build label to gitlab-ci includable https://github.com/T-Systems-MMS/docker-management-container/pull/92

**Comment by avalor1** [comment]
Thanks, it actually did work. I forgot to mention it here 🙈
